### ISSUE TITLE
How to demo this?

### ISSUE THREAD

**Issue by matthannam** [saalikmubeen/talkhouse#3]
This is a great project.  

What's the best way to demo this?  I keep getting stuck with "Sorry, the user you are trying to invite doesn't exist".  

<img width="1616" alt="Screen Shot 2022-04-26 at 12 30 57 PM" src="https://user-images.githubusercontent.com/16478966/165349016-832012ac-7a6b-4c2b-945a-06e524f0b7f3.png">

**Comment by saalikmubeen** [comment]
Thanks man. I appreciate you took the time and tried it in your local machine. 
 You are getting this message because the email you are trying to invite isn't a part of Talkhouse.  Open the app in two different browsers and register using two different email ids. And then invite one email from the other. 
:)

**Comment by matthannam** [comment]
Sorry, that seems obvious now...thanks!
